### ISSUE TITLE
Remove code from Assignment 28: Models

### ISSUE THREAD

**Issue by pareidoliax** [tadeosss/bloccit#10]
- [ ] Remove Answer Model
  - Migration
  - Model Spec
  - Model File
- [ ] Remove Question Model
  - Migration
  - Model Spec
  - Model File

**Comment by tadeosss** [comment]
Just wondering, shouldn't I delete these two models from the master branch? Since they were created on assignment 28 branch?

**Comment by pareidoliax** [comment]
Yes, delete them on a checkpoint branch and when that branch is merged into master they will be deleted there too.

**Comment by tadeosss** [comment]
Fixed issue #10.
